### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheMultii** [TheMultii/MarkdownNotepad#1]
- [x] użytkownicy
  - [x] rejestracja
  - [x] logowanie
  - ~~przypominanie hasła~~
  - [x] edycja profilu
  - [x] edycja avataru
  - [x] back-end
- [x] foldery
  - [x] dodawanie do folderów
    - [x] z poziomu notatki
    - [x] z poziomu folderu
  - [x] usuwanie z folderów
    - [x] z poziomu notatki
    - [x] z poziomu folderu
  - [x] tworzenie
  - [x] wyświetlanie folderów
  - [x] zmiana nazwy folderu
  - [x] usuwanie folderu (jeśli pusty)
  - [x] back-end
  - [x] ui 
- [x] tagi notatek
  - [x] przypisywanie do notatek
  - [x] usuwanie z notatek
  - [x] tworzenie
  - [x] edytowanie (?)
  - [x] back-end
  - [x] ui
- [x] notatki
  - [x] tworzenie
  - [x] edycja
    - [x] live share (socket.io)
      - [x] udostępnianie notatki
      - [x] alert dialog z id notatki do skopiowania i udostępnienia jej komuś
      - [x] możliwość dołączenia przez `Ctrl+Shift+P`
      - [x] łączenie się z serwerem liveshare
      - [x] edytowanie
      - [x] rozłączanie się z serwerem liveshare
      - [x] aktualna pozycja kursora użytkownika
        - [x] wyświetlanie
        - [x] informowanie o aktualizacji
        - [x] back-end
    - [x] edycja bez live share (PATCH)
    - [x] pytanie użytkownika, czy chce nadpisać notatkę, gdy jego wersja lokalna jest nowsza niż ta znajdująca się na serwerze
  - ~~szyfrowanie~~
  - [x] usuwanie
  - [x] eksportowanie do pdf/md
  - [x] kompilowanie do widżetów
  - [x] wsparcie dla wbudowanych rozszerzeń składni markdown
  - [x] back-end
  - [x] ui
- [x] event logi
  - [x] tworzenie po stronie back-endu
  - [x] wyświetlanie po stronie front-endu
    - [x] dashboard
    - [x] account 
  - [x] ui
- [x] rozszerzenia
  - [x] importowanie
  - [x] sprawdzanie poprawności pliku importowanego
  - [x] wyświetlanie szczegółów
  - [x] wyłączanie
  - [x] usuwanie
  - [x] implementacja w kompilowanie notatek
  - [x] ui
  - [x] wsparcie dla wbudowanych rozszerzeń składni markdown
- [x] inne
  - [x] wyświetlanie `userme` w drawerze
  - [x] wyszukiwarka `Ctrl+Shift+P`
    - [x] uruchamianie skrótem klawiszowym
    - [x] funkcjonowanie 
  - [x] skróty klawiszowe w edytorze notatek
    - [x] `Ctrl+F` (zaimplementowane domyślnie w edytor)
    - [x] `Ctrl+1` - utworzenie/usunięcie nagłówka h1, etc.  
   - [x] system powiadomień in-app
   - [x] lokalna baza danych (Hive)
   - [x] wsparcie dla providerów 
   - [x] doprowadzenie aplikacji do używalności na telefonach
   - [x] `Modular.to.navigate()` wynieść do osobnej helper klasy, która automatycznie ustawi też current tab w drawerze
